# Use root/example as user/password credentials
version: '3.1'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - .nginx/static:/usr/share/nginx/html/static
  app:
    build: .
    ports:
      - 5000:5000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tasks
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
