name: CI

on:
  push:
    branches: [ "master", "devops"]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pushd application/
        python -m pip install --upgrade pip
        pip install -r pytest-requirments.txt
    - name: Build the Docker compose
      run: docker compose -f application/docker-compose.yml up -d
    - name: Test with pytest
      run: |
        pytest application/

    

    
