name: CI

on:
  push:
    branches: [ "master", "devops"]
  pull_request:
    branches: [ "master" ]

# on: push

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
    - uses: actions/checkout@v3

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: ${{ matrix.python-version }}

    # - name: Install dependencies
    #   run: |
    #     pushd application/
    #     python -m pip install --upgrade pip
    #     pip install -r pytest-requirments.txt

    # - name: Build the Docker compose
    #   run: docker compose -f application/docker-compose.yml up -d

    # - name: Test with pytest
    #   run: |
    #     sleep 5
    #     pytest application/

## Calculate Version only if on main
    - name: Bump version and push tag
      # Will be changed to master soon
      if: ${{ github.ref == 'refs/heads/devops' }}
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 1.0.0
        DEFAULT_BRANCH: devops

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}






 

    

    

    
