
# example 2: on merge to master
name: Bump version
on:
  push:
    branches:
      - devops
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.55.0 # Don't use @master unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 1.0.0
    - name: Echo outputs
      run: |
        echo "new_version: $(git describe --tags)"
# echo "tag: ${{ tag }}"
# echo "part: ${{ part }}"
